AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false